############# 简体中文 导航 ##############

# 主菜单
[[main]]
identifier = "home"
name = "首页"
url = "/"
weight = 1

[[main]]
identifier = "blog"
name = "博客"
url = "/blog"
weight = 2

[[main]]
identifier = "categories"
name = "分类"
url = "/categories"
weight = 3

[[main]]
identifier = "tags"
name = "标签"
url = "/tags"
weight = 4

[[main]]
identifier = "authors"
name = "作者"
url = "/authors"
weight = 5


# 页脚菜单
[[footer]]
identifier = "about"
name = "关于"
url = "/about"
weight = 1

[[footer]]
identifier = "contact"
name = "联系"
url = "/contact"
weight = 2

[[footer]]
identifier = "elements"
name = "元素"
url = "/elements"
weight = 3

[[footer]]
identifier = "privacy"
name = "隐私政策"
url = "/privacy-policy"
weight = 4
